### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by chrisspen** [WesleyTo/subvocalization_stream#3]
Where did you leave off with this project? Has this essentially been abandoned due to lack of results? Do the sensors and software work at all?

**Comment by WesleyTo** [comment]
@chrisspen Both I and the other contributor left 42 Robotics Lab (and with it this project) in late 2018. IIRC, we had some preliminary results with `Yes`/`No` achieving ~80% accuracy. The project was carried on after we left, but I don't have status updates on it. I've updated the readme to include as much info as I can about the project in case anyone wants to follow up with the folks who continued it afterwards.
